FROM python:3.11

LABEL maintainer="NoobstrGTR"

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /backend

COPY requirements.txt requirements.txt
RUN venv/bin/pip install --no-cache-dir -r requirements.txt && \
    venv/bin/pip install --upgrade pip

COPY . /backend

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
